# =============================================================
#  AZURE DEVOPS / DATAOPS / NETWORK ADMIN PRO VM
#  Ubuntu 22.04 LTS - Azure Students Subscription
# =============================================================

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.90"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.5"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.4"
    }
    http = {
      source  = "hashicorp/http"
      version = "~> 3.4"
    }
    cloudinit = {
      source  = "hashicorp/cloudinit"
      version = "~> 2.3"
    }
  }
}

# ─── Détection automatique de l'IP publique du déployeur ─────
# Permet de restreindre SSH/Jupyter/Grafana/etc. sans étape manuelle
# quand allowed_ssh_cidr = "auto" (valeur par défaut, voir variables.tf).
data "http" "my_ip" {
  count = var.allowed_ssh_cidr == "auto" ? 1 : 0
  url   = "https://ifconfig.me/ip"
}

locals {
  # CIDR effectif utilisé par le NSG : IP auto-détectée, valeur fournie,
  # ou "*" si l'utilisateur l'a explicitement demandé.
  effective_ssh_cidr = var.allowed_ssh_cidr == "auto" ? "${trimspace(data.http.my_ip[0].response_body)}/32" : var.allowed_ssh_cidr

  data_disk_lun = 10

  # Indique, pour le profil choisi, quelles familles d'outils sont actives.
  # "fullstack" active tout ; sinon seul le profil demandé (+ le socle
  # commun, toujours installé côté cloud-init) est activé. Utilisé ici
  # pour n'ouvrir dans le NSG que les ports des services réellement
  # installés par cloud-init/install.sh (voir should_run() dans le script).
  profile_devops        = var.vm_profile == "devops" || var.vm_profile == "fullstack"
  profile_dataops       = var.vm_profile == "dataops" || var.vm_profile == "fullstack"
  profile_cybersecurity = var.vm_profile == "cybersecurity" || var.vm_profile == "fullstack"

  # En-tête injecté avant le script cloud-init : transmet à la VM les
  # valeurs choisies côté Terraform (nom d'utilisateur, mots de passe
  # générés, numéro de LUN du disque de données, profil) sans avoir à
  # templater (et donc risquer de casser) l'intégralité du script bash.
  cloud_init_header = <<-EOT
    #!/bin/bash
    export ADMIN_USER="${var.admin_username}"
    export GRAFANA_ADMIN_PASSWORD="${random_password.grafana.result}"
    export JUPYTER_TOKEN="${random_password.jupyter_token.result}"
    export PORTAINER_ADMIN_PASSWORD="${random_password.portainer.result}"
    export DATA_DISK_LUN="${local.data_disk_lun}"
    export VM_PROFILE="${var.vm_profile}"
  EOT

  # Le fichier install.sh a lui-même un shebang en première ligne ; on
  # le retire pour ne pas avoir un deuxième "#!/bin/bash" au milieu du
  # script (inoffensif en bash, mais on préfère un fichier propre).
  install_script_body = join("\n", slice(split("\n", file("${path.module}/cloud-init/install.sh")), 1, length(split("\n", file("${path.module}/cloud-init/install.sh")))))
}

# ─── Cloud-init compressé ────────────────────────────────────
# Le script d'installation complet (~40 outils) dépasse la limite Azure
# de 64 Ko pour custom_data. Le provider cloudinit compresse le contenu
# en Gzip avant encodage Base64, ce qui réduit typiquement la taille de
# 70-80 % et permet de rester sous la limite.
data "cloudinit_config" "vm_init" {
  gzip          = true
  base64_encode = true

  part {
    content_type = "text/x-shellscript"
    filename     = "install.sh"
    content = join("\n", [
      local.cloud_init_header,
      local.install_script_body
    ])
  }
}

# ─── Resource Group ──────────────────────────────────────────
resource "azurerm_resource_group" "rg" {
  name     = var.resource_group_name
  location = var.location
  tags     = var.tags
}

# ─── Random suffix (unique names) ────────────────────────────
resource "random_string" "suffix" {
  length  = 6
  special = false
  upper   = false
}

# ─── SSH Key pair (generated by Terraform) ───────────────────
resource "tls_private_key" "ssh" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "local_sensitive_file" "private_key" {
  content         = tls_private_key.ssh.private_key_pem
  filename        = "${path.module}/keys/${var.vm_name}_id_rsa"
  file_permission = "0600"
}

resource "local_file" "public_key" {
  content  = tls_private_key.ssh.public_key_openssh
  filename = "${path.module}/keys/${var.vm_name}_id_rsa.pub"
}

# ─── Identifiants générés automatiquement (0 étape manuelle) ─
# Grafana, Jupyter et Portainer ne restent plus jamais sur des
# identifiants par défaut (admin/admin, token vide...). Récupérables
# ensuite via `terraform output grafana_admin_password` etc.
resource "random_password" "grafana" {
  length  = 20
  special = false
}

resource "random_password" "jupyter_token" {
  length  = 32
  special = false
}

resource "random_password" "portainer" {
  length  = 20
  special = true
  # Portainer impose un jeu de caractères restreint pour son mot de passe initial
  override_special = "-_"
}

# ─── Storage Account (boot diagnostics) ──────────────────────
resource "azurerm_storage_account" "diag" {
  name                     = "diag${random_string.suffix.result}"
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  tags                     = var.tags
}

# ─── Public IP ───────────────────────────────────────────────
resource "azurerm_public_ip" "pip" {
  name                = "${var.vm_name}-pip"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  allocation_method   = "Static"
  sku                 = "Standard"
  domain_name_label   = "${var.vm_name}-${random_string.suffix.result}"
  tags                = var.tags
}

# ─── Network Interface ────────────────────────────────────────
resource "azurerm_network_interface" "nic" {
  name                = "${var.vm_name}-nic"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location

  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.subnet.id
    private_ip_address_allocation = "Static"
    private_ip_address            = var.vm_private_ip
    public_ip_address_id          = azurerm_public_ip.pip.id
  }
  tags = var.tags
}

# ─── Associate NIC → NSG ─────────────────────────────────────
resource "azurerm_network_interface_security_group_association" "nic_nsg" {
  network_interface_id      = azurerm_network_interface.nic.id
  network_security_group_id = azurerm_network_security_group.nsg.id
}

# ─── Virtual Machine ─────────────────────────────────────────
resource "azurerm_linux_virtual_machine" "vm" {
  name                  = var.vm_name
  resource_group_name   = azurerm_resource_group.rg.name
  location              = azurerm_resource_group.rg.location
  size                  = var.vm_size
  admin_username        = var.admin_username
  network_interface_ids = [azurerm_network_interface.nic.id]

  disable_password_authentication = true

  admin_ssh_key {
    username   = var.admin_username
    public_key = tls_private_key.ssh.public_key_openssh
  }

  os_disk {
    name                 = "${var.vm_name}-osdisk"
    caching              = "ReadWrite"
    storage_account_type = "Premium_LRS"
    disk_size_gb         = var.os_disk_size_gb
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts-gen2"
    version   = "latest"
  }

  boot_diagnostics {
    storage_account_uri = azurerm_storage_account.diag.primary_blob_endpoint
  }

  # Injecte le script cloud-init compressé en Gzip et encodé en Base64.
  # Le provider cloudinit gère automatiquement la compression, ce qui
  # permet de rester sous la limite Azure de 64 Ko pour custom_data.
  custom_data = data.cloudinit_config.vm_init.rendered

  tags = var.tags
}

# ─── Extra Data Disk (100 GB for projects/data) ──────────────
resource "azurerm_managed_disk" "data" {
  name                 = "${var.vm_name}-datadisk"
  location             = azurerm_resource_group.rg.location
  resource_group_name  = azurerm_resource_group.rg.name
  storage_account_type = "Premium_LRS"
  create_option        = "Empty"
  disk_size_gb         = var.data_disk_size_gb
  tags                 = var.tags
}

resource "azurerm_virtual_machine_data_disk_attachment" "data" {
  managed_disk_id    = azurerm_managed_disk.data.id
  virtual_machine_id = azurerm_linux_virtual_machine.vm.id
  lun                = local.data_disk_lun
  caching            = "ReadWrite"
}
